name: shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'compose-cd'

jobs:
  shellcheck:
    name: shellcheck with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.13.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added
          fail_on_error: true
          reporter: github-pr-review
          pattern: "compose-cd"
